### ISSUE TITLE
Destroy cache on close?

### ISSUE THREAD

**Issue by erikogabrielsson** [anibali/pyisyntax#9]
Should the cache be destroyed on `close()`? Maybe
```python
if self._cache is not None and not self._cache.destroyed:
    self._cache.destroy()
````

**Comment by anibali** [comment]
Fixed in https://github.com/anibali/pyisyntax/commit/8fe4c9475139b73b0e81041cc699fab0d54fcda6

Note that this issue isn't as big as it may initially seem, as cache objects are automatically destroyed when they are garbage collected. The code change simply removes the reference to the cache when an ISyntax object is closed. This leaves room for potential cache object reuse in the future.
